#' @title Processing script to grab catchment attributes
#' @author Guy Litt \code{guy.litt@noaa.gov}
#' @description
#' Given catchment location data generated by fsds_proc and a user-specified
#' configuration file for datasets and corresponding attributes of interest,
#' acquire the attributes for each catchment, write to parquet database.
#' @details Builds a parquet database for each individual comid when calling
#' \code{proc.attr.hydfab::proc_attr_wrap}. From the directory of comids,
#' creates a sub-directory of a specific dataset.
#'
#' NOTE: In defining the featureSource and featureID, it's expected that the
#' term 'gage_id' is used as a variable in glue syntax to create featureID
#' @seealso [fsds_proc] A python package that processes input data for the
#' formulation-selector

# Changelog / Contributions
#   2024-07-24 Originally created, GL
#.  2024-08-12 Add loc_id_read capability, GL
library(tibble)
library(yaml)
library(ncdf4)
library(proc.attr.hydfab)
library(glue)
library(tools)
# TODO is AWS_NO_SIGN_REQUEST necessary??
# Sys.setenv(AWS_NO_SIGN_REQUEST="YES")


# Define input directory:
raw_config <- yaml::read_yaml("/Users/guylitt/git/fsds/scripts/eval_ingest/xssa/xssa_attr_config.yaml") # Example that performs both fsds_proc and single locations dataset option
# raw_config <- yaml::read_yaml("/Users/guylitt/git/fsds/scripts/eval_ingest/xssa/loc_file_attr_config.yaml") # Example for only reading in locations from a single dataset

# A listing of datasets to grab attributes:
datasets <- unlist(raw_config$formulation_metadata)[['datasets']]# c("juliemai-xSSA",'all')[1]  Dataset names match what is inside dir_std_base.  'all' processes all datasets inside dir_std_base.

# The following dirs must use glue() for more glue() calls inside Retr_Params
home_dir <- Sys.getenv("HOME") # just-in-case {home_dir} is specified in any of the raw_config$file_io paths.
dir_base <- glue::glue(unlist(raw_config$file_io)[['dir_base']])
dir_std_base <- glue::glue(unlist(raw_config$file_io)[['dir_std_base']]) #file.path(dir_base,"input","user_data_std") # The location of standardized data generated by proc_fsds python package
dir_hydfab <- glue::glue(unlist(raw_config$file_io)[['dir_db_hydfab']]) #file.path(dir_base,'input','hydrofabric') # The local dir where hydrofabric data are stored to limit s3 connections
dir_db_attrs <- glue::glue(unlist(raw_config$file_io)[['dir_db_attrs']]) # file.path(dir_base,'input','attributes') # The parent dir where each comid's attribute parquet file is stored in the subdirectory 'comid/', and each dataset's aggregated parquet attributes are stored in the subdirectory '/{dataset_name}

# ----------------- Hydrofabric config -----------------
s3_base <- glue::glue(unlist(raw_config$hydfab_config)[['s3_base']])#"s3://lynker-spatial/tabular-resources" # s3 path containing hydrofabric-formatted attribute datasets
s3_bucket <- glue::glue(unlist(raw_config$hydfab_config)[['s3_bucket']]) # s3 bucket containing hydrofabric data
hf_cat_sel <- unlist(raw_config$hydfab_config)[['hf_cat_sel']] #c("total","all")[1] # total: interested in the single location's aggregated catchment data; all: all subcatchments of interest
ext <- unlist(raw_config$hydfab_config)[['ext']] #'gpkg'

# ----------------- Variable config -----------------
s3_path_hydatl <- glue::glue(unlist(raw_config$attr_select)[['s3_path_hydatl']]) # path to hydroatlas data formatted for hydrofabric

idxs_vars <- base::lapply(raw_config$attr_select, function(x) names(x)) %>%
              base::unlist() %>% base::grep(pattern = "_vars")

ls_vars <- base::sapply(idxs_vars, function(x) raw_config$attr_select[[x]])

# The standardized variable names as expected in proc.attr.hydfab package:
ha_vars <- unlist(ls_vars$ha_vars) #c('pet_mm_s01', 'cly_pc_sav', 'cly_pc_uav') # hydroatlas variables
sc_vars <- unlist(ls_vars$sc_vars) #c() # TODO look up variables. May need to select datasets first
usgs_vars <- unlist(ls_vars$usgs_vars) #c('TOT_TWI','TOT_PRSNOW','TOT_POPDENS90','TOT_EWT','TOT_RECHG') # list of variables retrievable using nhdplusTools::get_characteristics_metadata()
#-----------------------------------------------------

# Generate the parameter retrieval list: a listing structure based on what is
#   provided in yaml config file & accounting for empty entries

Retr_Params <- list(paths = list(# Note that if a path is provided, ensure the
  # name includes 'path'. Same for directory having variable name with 'dir'
                        dir_hydfab=dir_hydfab,
                        dir_db_attrs=dir_db_attrs,
                        s3_path_hydatl = s3_path_hydatl,
                        dir_std_base = dir_std_base),
                   vars = list(usgs_vars = usgs_vars,
                               ha_vars = ha_vars,
                               sc_vars = sc_vars),
                   data_fmt = list(
                              featureID = base::unlist(raw_config$col_schema)[['featureID']],
                              featureSource = base::unlist(raw_config$col_schema)[['featureSource']]
                               ),
                   file_io = unlist(raw_config$file_io),
                   datasets = datasets
       )
# In case a separate file exists containing location ids that need attributes
if (!base::is.null(raw_config$loc_id_read)){
  idxs_loc_id <- base::seq(base::length(raw_config$loc_id_read))
  # Convert to a list of names to avoid having to depend on indexed location
  vars_loc_id <- base::sapply(idxs_loc_id, function(x)
    raw_config$loc_id_read[[x]])
  # Add the location-id specific parameters to the parameter retrieval list
  Retr_Params$loc_id_read <- list(
    gage_id = vars_loc_id$gage_id,
    loc_id_filepath = glue::glue(vars_loc_id$loc_id_filepath),
    featureID_loc = vars_loc_id$featureID_loc,
    featureSource_loc = vars_loc_id$featureSource_loc,
    fmt = tools::file_ext(vars_loc_id$loc_id_filepath))
}

ls_comids <- proc.attr.hydfab:::grab_attrs_datasets_fsds_wrap(Retr_Params)

# --------------------------- Compile attributes --------------------------- #
# Demonstration of how to retrieve attributes/comids that exist inside dir_db_attrs:
# The comids of interest
comids <- ls_comids %>% base::unname() %>% base::unlist()

# The attribute variables of interest
vars <- Retr_Params$vars %>% base::unlist() %>% base::unname()

dat_all_attrs <- proc.attr.hydfab::retrieve_attr_exst(comids, vars,
                                                      Retr_Params$paths$dir_db_attrs)
base::rm(dat_all_attrs)
