#' @title Processing script to grab catchment attributes
#' @author Guy Litt \code{guy.litt@noaa.gov}
#' @description
#' Given catchment location data generated by fsds_proc and a user-specified
#' configuration file for datasets and corresponding attributes of interest,
#' acquire the attributes for each catchment, write to parquet database.
#' @details Builds a parquet database for each individual comid when calling
#' \code{proc.attr.hydfab::proc_attr_wrap}. From the directory of comids,
#' creates a sub-directory of a specific dataset.
#'
#' NOTE: In defining the featureSource and featureID, it's expected that the
#' term 'gage_id' is used as a variable in glue syntax to create featureID
#' @seealso [fsds_proc] A python package that processes input data for the
#' formulation-selector

# Changelog / Contributions
#   2024-07-24 Originally created, GL

library(tibble)
library(yaml)
library(ncdf4)
library(proc.attr.hydfab)
library(glue)
# TODO is AWS_NO_SIGN_REQUEST necessary??
# Sys.setenv(AWS_NO_SIGN_REQUEST="YES")

# TODO create config yaml.

# TODO read in config yaml, must populate NA for items that are empty.

# Define input directory:
# TODO change this to reading the standardized metadata, not the generated data

# raw_config <- yaml::read_yaml("/Users/guylitt/git/formulation-selector/scripts/eval_ingest/xssa/xssa_attr_config.yaml")
raw_config <- yaml::read_yaml("/Users/guylitt/git/formulation-selector/scripts/eval_ingest/SI/SI_attr_config.yaml")


datasets <- ds <- raw_config$formulation_metadata[[grep("datasets",raw_config$formulation_metadata)]]$datasets#c("juliemai-xSSA",'all')[1] # A listing of datasets to grab attributes. Dataset names match what is inside dir_std_base.  'all' processes all datasets inside dir_std_base.
#ds_nc_filenames <- c('juliemai-xSSA_Raven_blended.nc','*.nc')[1]


home_dir <- Sys.getenv("HOME")
dir_base <- file.path(home_dir,'noaa','regionalization','data')

dir_std_base <- file.path(dir_base,"input","user_data_std") # The location of standardized data generated by proc_fsds python package
dir_db_hydfab <- file.path(dir_base,'input','hydrofabric') # The local dir where hydrofabric data are stored to limit s3 connections
dir_db_attrs <- file.path(dir_base,'input','attributes') # The parent dir where each comid's attribute parquet file is stored in the subdirectory 'comid/', and each dataset's aggregated parquet attributes are stored in the subdirectory '/{dataset_name}


s3_base <- "s3://lynker-spatial/tabular-resources" # s3 path containing hydrofabric-formatted attribute datasets
s3_bucket <- 'lynker-spatial' # s3 bucket containing hydrofabric data

s3_path_hydatl <- glue::glue('{s3_base}/hydroATLAS/hydroatlas_vars.parquet') # path to hydroatlas data formatted for hydrofabric

# Additional config options
hf_cat_sel <- c("total","all")[1] # total: interested in the single location's aggregated catchment data; all: all subcatchments of interest
ext <- 'gpkg'
attr_sources <- c("hydroatlas","usgs") # "streamcat",
# TODO communicate to user that these are standardized variable names
ha_vars <- c('pet_mm_s01', 'cly_pc_sav', 'cly_pc_uav','cly_pc_sav','ari_ix_sav') # hydroatlas variables
sc_vars <- c() # TODO look up variables. May need to select datasets first
usgs_vars <- c('TOT_TWI','TOT_PRSNOW','TOT_POPDENS90','TOT_EWT','TOT_RECHG','TOT_PPT7100_ANN','TOT_AET','TOT_PET','TOT_SILTAVE','TOT_BASIN_AREA','TOT_BASIN_SLOPE','TOT_ELEV_MEAN','TOT_ELEV_MAX','TOT_Intensity','TOT_Wet','TOT_Dry' ) # list of variables retrievable using nhdplusTools::get_characteristics_metadata()
#-----------------------------------------------------

# TODO generate this listing structure based on what is provided in yaml config
#   & accounting for empty entries

Retr_Params <- list(paths = list(# Note that if a path is provided, ensure the
  # name includes 'path'. Same for directory having variable name with 'dir'
                        dir_db_hydfab=dir_db_hydfab,
                        dir_db_attrs=dir_db_attrs,
                        s3_path_hydatl = s3_path_hydatl,
                        dir_std_base = dir_std_base),
                   vars = list(usgs_vars = usgs_vars,
                               ha_vars = ha_vars,
                               sc_vars = sc_vars),
                   datasets = datasets
       )

ls_comids <- proc.attr.hydfab:::grab_attrs_datasets_fsds_wrap(Retr_Params,overwrite = TRUE)

# --------------------------- Compile attributes --------------------------- #
# Demonstration of how to retrieve attributes/comids that exist inside dir_db_attrs:
# The comids of interest
comids <- ls_comids %>% base::unname() %>% base::unlist()

# The attribute variables of interest
vars <- Retr_Params$vars %>% base::unlist() %>% base::unname()

dat_all_attrs <- proc.attr.hydfab::retrieve_attr_exst(comids, vars,
                                                      Retr_Params$paths$dir_db_attrs)
base::rm(dat_all_attrs)
